controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /api/auth
    methods: ['POST']

api_login_check:
     path: /api/login_check
     stateless: false

#Route pour rafraichir notre JWT
api_refresh_token:
    path: /api/token/refresh

#Route pour invalider notre token de rafraichissement (le supprimer). utile pour se "déconnecter" réellement.
api_token_invalidate:
    path: /api/token/invalidate
